### ISSUE TITLE
Concat both CSS + JS?

### ISSUE THREAD

**Issue by shipstar** [sapegin/grunt-bower-concat#17]
I'm trying to use grunt-bower-concat for a pretty simple build system. Everything was going swimmingly until I added a component that contained both CSS and JS (namely https://github.com/vitalets/angular-xeditable).

The bower_concat section of my Gruntfile (.coffee) just has

```
bower_concat:
  all:
    dest: 'build/components.js'
```

angular-xeditable has a bower.json file with the following lines:

```
"main": [
  "dist/css/xeditable.css",
  "dist/js/xeditable.js"
]
```

I'd like to be able to concatenate the `xeditable.css` into `components.css` and `xeditable.js` into `components.js`.

It seems like a reasonable solution would be something like

```
bower_concat:
  all:
    dest:
      js: 'build/components.js'
      css: 'build/components.css'
```

or

```
bower_concat:
  js:
    dest: 'build/components.js'
  css:
    dest: 'build/component.css'
```

I'm fairly new to Grunt and even newer to grunt-bower-concat, so I might be way off base here. Is this something that's in the pipeline? Am I missing something obvious?

**EDIT**: Replace bootstrap-stylus with angular-xeditable just to avoid any stylus-related confusion.
